name: CI

on: [push]

jobs:
  # build:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Run a one-line script
  #     run: echo Hello, world!
  #   - name: Run a multi-line script
  #     run: |
  #       echo Add other actions to build,
  #       echo test, and deploy your project.
  #       echo $DEPLOY_PASS
  #       env

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        # username: ${{ secrets.deploy_un }}
        # # password: ${{ secrets.deploy_pass }}
        # password: "someeincorrectpassword"
        key: ${{ secrets.deploy_key }}
        host: 138.197.68.192
        script: echo "Testing"