name: CI

on: [push]

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        # username: ${{ secrets.deploy_un }}
        # # password: ${{ secrets.deploy_pass }}
        # password: "someeincorrectpassword"
        username: root
        key: ${{ secrets.deploy_key }}
        host: 138.197.68.192
        script: echo "Testing"