name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    env: # Or as an environment variable
      deploy_un: ${{ secrets.deploy_un }}
      deploy_pass: ${{decrets.deploy_pass }}

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
        echo $deploy_un

