name: CI

on: [push]

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        username: root
        key: ${{ secrets.deploy_key }}
        host: 138.197.68.192
        script: |


          if [ -d "drawdown-frontend" ]; then
            cd drawdown-frontend
            git pull
          else 
            apt-get install update
            apt-get install docker.io
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs

            git clone https://github.com/Kolbeckenstein/drawdown-frontend.git
            cd drawdown-frontend
          fi

          npm install gatsby-cli
          gatsby build
          docker build -t drawdown-frontend .
          docker run -d -p 80:80 drawdown-frontend