name: CI

on: [push]

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        CMS_API_KEY: ${{ secrets.cms_api_key }}
        FOO: "BAR"
      with:
        username: root
        key: ${{ secrets.deploy_key }}
        host: 138.197.68.192
        envs: CMS_API_KEY,FOO
        script: |
          env
          echo "TestValue=$CSM_API_KEY"
          echo "BarValue=$FOO"
          if [ -d "drawdown-frontend" ]; then
            cd drawdown-frontend
            git fetch --all
            git reset --hard origin/master
          else 
            apt-get install update
            apt-get install docker.io
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs
            git clone https://github.com/Kolbeckenstein/drawdown-frontend.git
            cd drawdown-frontend
          fi
          npm install
          gatsby build
          docker build -t drawdown-frontend .
          docker stop drawdown-frontend
          docker rm drawdown-frontend
          docker run --name drawdown-frontend -d -p 80:80 drawdown-frontend
          docker system prune