name: CI

on: [push]

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        username: root
        key: ${{ secrets.deploy_key }}
        host: 138.197.68.192
        script: |
          ls -la
          pwd
          if [ -d "drawdown-frontend" ]; then
            cd drawdown-frontend
            git pull
          else 
            git clone https://github.com/Kolbeckenstein/drawdown-frontend.git
            cd drawdown-frontend
          fi
          ls -la
          pwd
          docker --help