name: CI

on: [push]

jobs:

  pipeline:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      env:
        CMS_USERNAME: "${{ secrets.cms_username }}"
        CMS_PASSWORD: "${{ secrets.cms_password }}"
      with:
        username: root
        key: ${{ secrets.deploy_key }}
        host: 138.197.68.192
        envs: CMS_API_KEY
        script: |
          if [ -d "drawdown-frontend" ]; then
            cd drawdown-frontend
            git fetch --all
            git reset --hard origin/master
          else 
            apt-get install update
            apt-get install docker.io
            curl -sL https://deb.nodesource.com/setup_13.x | sudo -E bash -
            sudo apt-get install -y nodejs
            git clone https://github.com/Kolbeckenstein/drawdown-frontend.git
            cd drawdown-frontend
          fi
          ./build.sh